Task 3
annmiro/cat-energy pull request #4
Opened 2023-05-22 15:18 UTC by annmiro

2023-05-22 18:18 UTC, demidemid requested changes

2023-05-22 18:18 UTC, demidemid commented on source/form.html
> +          <a class="site-list__link" site-list__link--current>Подбор программы</a>
класс вылетел

2023-05-22 18:18 UTC, demidemid commented on source/sass/blocks/header.scss
> +  padding: 20px 22px 0 24px;
у тебя тут отступ не общий у всего хедера, а отдельный у каждого блока, так как сепараторные линии должны быть разделителями, вот как на макете:
<img width="609" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/4e1a24da-490f-43ce-8a89-feb4a186b0da">

2023-05-22 18:18 UTC, demidemid commented on source/sass/blocks/sub-promo.scss
> +.sub-promo__text {
забыла обнулить margin-top, и не задан правильный margin-bottom
<img width="361" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/683ab90f-8e72-463f-b132-091b375fa55e">

2023-05-22 18:18 UTC, demidemid commented on source/sass/blocks/about.scss
> +  margin-bottom: 20px;
у тебя по макету текст должен отцентрован по вертикале относительно иконки, а сейчас он по верхней границе
<img width="602" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/3b43a817-87f5-4744-931d-741febd72116">

2023-05-22 18:18 UTC, demidemid commented on source/sass/blocks/about.scss
> +  margin-bottom: 20px;
не обнуляешь марджин у последнего элемента `li`

2023-05-22 18:18 UTC, demidemid commented on source/index.html
> +        <a class="footer__logo-link logo">
класс logo лишний, он ничего не делает

2023-05-22 18:18 UTC, demidemid commented on source/index.html
> +        <div class="copyright__wrapper">
эта обертка лишняя, можно этот класс назначить на ссылку `<a>` и свг логотип положить внутрь нее

2023-05-24 07:33 UTC, annmiro commented on source/sass/blocks/sub-promo.scss
> +.sub-promo__text {
margin-bottom здесь разве нужен? я изменила на padding + добавила border-bottom, как в макете
`.sub-promo__text 

> {.sub-promo__text {
  font-size: 14px;
  line-height: 18px;
  color: $dark-grey;
  margin-top: 0;
  padding-bottom: 22px;
  border-bottom: $separator-line-2;
}

2023-05-24 07:40 UTC, annmiro commented on source/sass/blocks/header.scss
> +  padding: 20px 22px 0 24px;
done

2023-05-24 08:04 UTC, annmiro commented on source/sass/blocks/about.scss
> +  margin-bottom: 20px;
done

2023-05-24 09:01 UTC, annmiro commented on source/index.html
> +        <div class="copyright__wrapper">
done

2023-05-26 14:50 UTC, demidemid commented on source/catalog.html
> +    <a class="header__logo-link logo" href="index.html">
logo — у этого класса нет стилей, если это задел на будущее оставь, если нет, то лучше удалить. 
в программированние считается, любой не используемый код — это мусор, который захламляет проект

2023-05-26 14:50 UTC, demidemid commented on source/catalog.html
> +          <p class="advertisement__description">Закажите все и получите чехол для кота в подарок!</p>
забыла обнулить отступ снизу, и сверху отступ тоже не нужен. это свг снизу должно толкать этот текст

мы же толкаем по потоку, сверху вниз, и слева на право

<img width="365" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/7e9e4864-229d-48c4-b342-f682e61a37fb">

2023-05-26 14:50 UTC, demidemid commented on source/catalog.html
> +      <section class="socials">
тут слишком большие отступы по краям, можно сделать по 30px этого вполне будет достаточно для переполнения контента

2023-05-26 14:50 UTC, demidemid commented on source/index.html
> +    <a class="header__logo-link logo">
тоже самое с logo, уже писал в catalog.html

2023-05-26 14:50 UTC, demidemid commented on source/sass/blocks/advertisement.scss
> +  color: #ffffff;
цвет нужно взять из переменной

2023-05-26 14:50 UTC, demidemid commented on source/sass/blocks/card.scss
> +
пустая строка, можно удалить

2023-05-26 14:50 UTC, demidemid commented on source/sass/blocks/contacts.scss
> +  background-image: url("../../images/Rectangle.jpg");
имя файла должно быть с маленькой буквы

2023-05-26 14:50 UTC, demidemid commented on source/sass/blocks/contacts.scss
> +  background-color: #aadaff;
почему переменную не используешь?

2023-05-26 14:50 UTC, demidemid commented on source/sass/blocks/products.scss
пустой файл, если не нужен, то можно удалить

2023-05-26 14:50 UTC, demidemid commented on source/sass/variables.scss
> +$grey: #D3D3D3;
1. grey — очень короткое название, не хватает как будто симантики, попробуй переименовать (опционально)

2. можно сгруппировать все серые цвета вместе, чтобы они не разбавлялись другими, а вырисовывалась палитра. еще можно выделить цвета по смыслу (текстовые, фоновые, сепараторные, без явной специфики), можно выделить просто по алфавиту. короче хочется какой-то структуры

2023-05-28 13:52 UTC, annmiro commented on source/catalog.html
> +          <p class="advertisement__description">Закажите все и получите чехол для кота в подарок!</p>
done

2023-05-28 14:01 UTC, annmiro commented on source/index.html
> +    <a class="header__logo-link logo">
удален

2023-05-28 15:09 UTC, annmiro commented on source/sass/variables.scss
> +$grey: #D3D3D3;
в процессе постараюсь структурировать

2023-05-30 08:50 UTC, demidemid requested changes

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/application.scss
> +  padding: 27px 20px 0;
padding по бокам оставь у `application__title`, а `padding-top` — это часть `application`

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +  white-space: nowrap;
```
white-space: nowrap;
flex-basis: 20%;
```
эти два свойства должны добавляться только у интпутов в которые вводится информация (фио, телефон, имейл), для радио баттонов и чекбоксов тест не должен при переполнение быть в 1 строчку без переноса

у тебя должно быть вот такое поведение:

<img width="343" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/85a1f725-ce2e-4425-972b-1ca4601ae23a">

а оно сейчас вот так:
<img width="343" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/bab59fc9-f347-4f2d-9ad9-c873439ee8bd">

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +    margin-left: 18px;
этот марджин не нужен, плюс тебе нужно сделать кастомный чекбокс по аналогии с радио кнопкой, через padding и абсолютное позиционирование (кастомного чекбока).

чтобы при переполнение контента чекбокс оставался по центру 1 строки текста, а не так как у тебя сейчас:

<img width="343" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/8f9ef642-4b57-469c-bb74-8492590854f8">

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +    gap: 20px;
придерживайся одной логики, если ты везде используешь для отступов между элементами марджин, не нужно где-то делать марджин, а где-то `gap` у родительского блока

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +    gap: 20px;
плюс этот отступ не верный по значению, он должен быть больше 

<img width="396" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/886f21df-d289-439c-9ae9-22e1f17e8b21">

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +    display: flex;
у тебя fieldset уже flex, второй раз не нужно писать

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/form.scss
> +  border-bottom: $separator-line-3;
у последнего элемента нужно обнулять этот отступ

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/contacts.scss
> +
удалить пустую строку

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/contacts.scss
> +  &--with-background {
забыла добавить в разметки у формы

2023-05-30 08:50 UTC, demidemid commented on source/form.html
> +    <a class="header__logo-link logo" href="index.html">
logo не удалила

2023-05-30 08:50 UTC, demidemid commented on source/form.html
> +                <span><svg class="form__icon" width="20" height="15">
зачем тут пустой `span`?
что-то не доделано?

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/advertisement.scss
> +  background-color: #6db043;
кажется тут можно было взять $basic-green, чтобы не плодить новые цвета

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/card.scss
> +  &::before {
можно вынести общие свойства из before и after как ты это сделала в radio button

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/checkbox.scss
> +.input-checkbox:checked+.checkbox::before {
добавь пробелы вокруг + для читабельности

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/radio.scss
> +.input-radio:checked+.radio::after {
пробелы вокруг плюсика

или это форматтер так сам делает потом?

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/socials.scss
> +  gap: 37px;
я бы использовал что-то одно, лучше сверстать проект полностью на марджинах, без гэпов

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/socials.scss
> +
пустая строка

2023-05-30 08:50 UTC, demidemid commented on source/sass/blocks/socials.scss
> +  gap: 40px;
тот же месседж про гэпы и марджины

2023-05-30 08:50 UTC, demidemid commented on source/sass/variables.scss
> +
одна пустая строка лишняя

2023-05-30 11:00 UTC, annmiro commented on source/sass/blocks/form.scss
> +    display: flex;
ok

2023-05-30 11:04 UTC, annmiro commented on source/sass/blocks/contacts.scss
> +  &--with-background {
добавила

2023-05-30 11:06 UTC, annmiro commented on source/sass/blocks/form.scss
> +  border-bottom: $separator-line-3;
отступ или бордер?

2023-05-31 08:24 UTC, annmiro commented on source/sass/blocks/application.scss
> +  padding: 27px 20px 0;
done

2023-05-31 09:41 UTC, annmiro commented on source/sass/blocks/form.scss
> +  white-space: nowrap;
эти 2 свойства у меня используются для одного из блоков с классом form-fieldset, т.к я не нашла доугого решения реализации нюанса макета. 
<img width="316" alt="Screenshot 2023-05-31 at 13 12 45" src="https://github.com/annmiro/cat-energy/assets/122688367/0e6a74d8-8b74-4f4f-9804-b39c7de113e2">
Могу создать модификатор, чтобы удалить эти свойства с чекбоксов и радиокнопок, или есть другое решение?

2023-05-31 09:57 UTC, annmiro commented on source/sass/blocks/form.scss
> +  white-space: nowrap;
done

2023-05-31 09:58 UTC, annmiro commented on source/sass/blocks/form.scss
> +    margin-left: 18px;
done

2023-05-31 10:28 UTC, annmiro commented on source/sass/blocks/form.scss
> +    gap: 20px;
done

2023-05-31 10:28 UTC, annmiro commented on source/form.html
> +    <a class="header__logo-link logo" href="index.html">
done

2023-05-31 10:32 UTC, annmiro commented on source/sass/blocks/checkbox.scss
> +.input-checkbox:checked+.checkbox::before {
бессмысленно, т.к автоматическое форматирование удаляет эти пробелы

2023-05-31 10:32 UTC, annmiro commented on source/sass/blocks/radio.scss
> +.input-radio:checked+.radio::after {
не добавлю. см.мой коммент выше

2023-05-31 10:34 UTC, annmiro commented on source/sass/blocks/socials.scss
> +
удалено.

2023-05-31 10:45 UTC, annmiro commented on source/sass/blocks/socials.scss
> +  gap: 37px;
done

2023-05-31 10:45 UTC, annmiro commented on source/sass/blocks/socials.scss
> +  gap: 40px;
done

2023-05-31 11:58 UTC, annmiro commented on source/sass/blocks/card.scss
> +  &::before {
done

2023-05-31 11:59 UTC, annmiro commented on source/sass/blocks/advertisement.scss
> +  background-color: #6db043;
done

2023-05-31 18:04 UTC, annmiro commented on source/form.html
> +                <span><svg class="form__icon" width="20" height="15">
done

2023-06-01 03:01 UTC, demidemid approved these changes

2023-06-01 07:12 UTC, merged