Task 5
annmiro/cat-energy pull request #6
Opened 2023-06-17 15:41 UTC by annmiro

2023-06-17 16:12 UTC, demidemid requested changes

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/promo.scss
>    margin-bottom: 138px;
тут нужно сбросить max-width

2023-06-17 16:12 UTC, demidemid commented on source/index.html
> +          <source srcset="images/logo-mobile.svg" media="(min-width:1440px)">
забыла подключить картинку для десктопа

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/footer.scss
> +    @include container;
забыла поменять padding  для десктопа

2023-06-17 16:12 UTC, demidemid commented on source/images/cat-desktop.png
это изображение не пригодится, его можно удалить

2023-06-17 16:12 UTC, demidemid commented on source/images/cat-tablet.png
это тоже нужно удалить

2023-06-17 16:12 UTC, demidemid commented on source/index.html
> -        <!-- <iframe
почему удалила?

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/range-slider.scss
> +  &::-webkit-slider-thumb {
нужно добавить префиксы для мозилы (фаерфокс) и майкрософт ие, они были в примере

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/promo.scss
> +      background-color: #414146;
такой цветовой переменной нет?

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/range-slider.scss
> +    background-color: #FFFFFF;
забыла цвет из переменной добавить

2023-06-17 16:12 UTC, demidemid commented on source/sass/blocks/range-slider.scss
> +      box-shadow: 0px 0px 0px 2px #CDCDCD;
#CDCDCD — можно вынести в переменную и использовать ее для перменной `$separator-line-3`

будет выглядеть вот так

```
$grey-bla-bla-color: #CDCDCD;
$separator-line-3: 1px solid $grey-bla-bla-color;
```

ну и тут ее заюзать

2023-06-18 11:16 UTC, annmiro commented on source/sass/blocks/promo.scss
>    margin-bottom: 138px;
ты ссылаешься на стили мобильной версии. max-width я задаю в планшетной версии для соответствия макету и в desktop max-width сбрасываю.

2023-06-18 11:24 UTC, annmiro commented on source/index.html
> +          <source srcset="images/logo-mobile.svg" media="(min-width:1440px)">
done

2023-06-18 11:25 UTC, annmiro commented on source/images/cat-desktop.png
done

2023-06-18 11:27 UTC, annmiro commented on source/index.html
> -        <!-- <iframe
gulp ругался

2023-06-18 11:28 UTC, annmiro commented on source/sass/blocks/range-slider.scss
> +    background-color: #FFFFFF;
добавила

2023-06-18 11:28 UTC, annmiro commented on source/sass/blocks/promo.scss
> +      background-color: #414146;
нет.  брали пипеткой

2023-06-19 10:39 UTC, annmiro commented on source/images/cat-tablet.png
done

2023-06-19 12:04 UTC, annmiro commented on source/sass/blocks/range-slider.scss
> +  &::-webkit-slider-thumb {
done

2023-06-19 13:01 UTC, annmiro commented on source/sass/blocks/range-slider.scss
> +  &::-webkit-slider-thumb {
done

2023-06-19 14:19 UTC, annmiro commented on source/sass/blocks/footer.scss
> +    @include container;
изменен

2023-06-19 14:24 UTC, annmiro commented on source/sass/blocks/range-slider.scss
> +      box-shadow: 0px 0px 0px 2px #CDCDCD;
вынесла все  оттенки серого в переменные. заметь, что в макете их тысяча оттенков и не хватает как фантазии, так и времени на раздумья, как назвать тот или иной оттенок (при том, что функционал они несут одинаковый)
поэтому они у меня различаются только цифрами 1, 2, 3 и тд...

2023-06-20 10:09 UTC, annmiro commented on source/sass/blocks/range-slider.scss
> +  &::-webkit-slider-thumb {
вернула прежние стили

2023-07-08 11:52 UTC, demidemid requested changes

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/catalog.scss
> +    font-size: 60px;
забыла обновить `line-height`

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/card.scss
> +    margin-right: 50px;
откуда взять такой большой отступ и для чего?
если ты сама его придумала, что бы названия в случае переполнения не прикасались к значениями, то тут достаточно будет отступа в 10-20px

2023-07-08 11:52 UTC, demidemid commented on source/catalog.html
> +        <li class="catalog__item catalog__item--main">
на строке с `<span class="card__item">На самом деле вкусов гораздо больше!</span>` — ошибка, этот класс должен называться у тебя `card__item-name`.

пишу тут, потому что git не позволяет у этой строки оставить комментарий

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/contacts.scss
> +    line-height: 20px;
на мобильной версии тоже 20, нет смысла менять на такое же значение

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/advertisement.scss
> +    width: unset;
по макету на планшете текст должен быть по правому краю, а у тебя он по центру идет с мобилы. 
а потом тут на десктопе он снова должен становится по центру

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/catalog.scss
> +      margin-right: 80px;
этот отступ должен быть не у каждого элемента `li`, а один раз у родителя — `ul`

2023-07-08 11:52 UTC, demidemid commented on source/catalog.html
> +    <div class="header__content">
общая ошибка всех блоков, поэтому тут напишу, чтобы не потерялось. нет большого отступа по бокам для десктопа (я про красные линии по бокам)

<img width="541" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/28067d08-f939-4503-8769-206eb5354960">

Т.е. заголовок Каталог и все остальные блоки должны начинаться на одном уровне с лого в хэддере, вот как у тебя:

<img width="1316" alt="image" src="https://github.com/annmiro/cat-energy/assets/24936371/b6ce6066-6ab4-4960-8e33-8a89ddf10343">

2023-07-08 11:52 UTC, demidemid commented on source/sass/blocks/products-additional.scss
> +      left: -110px;
тут кажется линия должна идти от края экрана

2023-07-08 11:52 UTC, demidemid commented on source/scripts.js
> +console.log(menuButton)
этот console.log забыли удалить

2023-07-09 15:46 UTC, annmiro commented on source/scripts.js
> +console.log(menuButton)
done

2023-07-09 15:53 UTC, annmiro commented on source/sass/blocks/catalog.scss
> +    font-size: 60px;
done

2023-07-14 07:22 UTC, annmiro commented on source/sass/blocks/catalog.scss
> +      margin-right: 80px;
скорректировала

2023-07-14 07:25 UTC, annmiro commented on source/sass/blocks/card.scss
> +    margin-right: 50px;
скорректировала

2023-07-14 07:27 UTC, annmiro commented on source/sass/blocks/contacts.scss
> +    line-height: 20px;
удалила

2023-07-14 09:00 UTC, annmiro commented on source/sass/blocks/advertisement.scss
> +    width: unset;
done

2023-07-14 11:06 UTC, annmiro commented on source/catalog.html
> +    <div class="header__content">
пофиксила

2023-07-14 11:07 UTC, annmiro commented on source/sass/blocks/products-additional.scss
> +      left: -110px;
доработала, посмотри

2023-07-14 11:10 UTC, annmiro commented on source/catalog.html
> +        <li class="catalog__item catalog__item--main">
не поняла комментарий

2023-07-17 07:18 UTC, demidemid approved these changes

2023-07-28 13:16 UTC, demidemid requested changes

2023-07-28 13:16 UTC, demidemid commented on source/catalog.html
>                    <img class="card__image" src="images/catalog-5-desktop.png"
тут не забыла картинку поменять? по умолчанию у тебя везде же должна быть мобильная версия 1x

2023-07-28 13:16 UTC, demidemid commented on source/catalog.html
> +
не нужный пропуск строки )

2023-07-28 13:16 UTC, demidemid commented on source/index.html
>          <source srcset="images/index-can-tablet.jpg" media="(min-width:768px)">
забыла указать ретину для десктопа и планшета

2023-07-28 13:16 UTC, demidemid commented on source/index.html
>          <source srcset="images/index-can-tablet.jpg" media="(min-width:768px)">
плюс нейминг неверный у файлов

2023-07-28 15:22 UTC, annmiro commented on source/catalog.html
> +
ты ведь сам скрипт прописывал))

2023-07-28 15:28 UTC, annmiro commented on source/catalog.html
>                    <img class="card__image" src="images/catalog-5-desktop.png"
изменила

2023-07-31 14:40 UTC, annmiro commented on source/index.html
>          <source srcset="images/index-can-tablet.jpg" media="(min-width:768px)">
выполнено

2023-08-01 19:28 UTC, demidemid approved these changes

2023-08-01 19:30 UTC, merged